name: power-reader
global:
  registry: harbor.crazyzone.be/crazyzone
  image: power-readout
  tag: 0.0.14
  #Use an existing secret for your registry
  #existingRegisrySecret: ""
device:
  path: /dev/ttyUSB0
resources:
  replicaCount: 1
hostnames:
  - power-reader.crazyzone.be
tolerations:
  - key: "type"
    value: "power"
    operator: "Equal"
    effect: "NoSchedule"
ingress:
  enabled: true
  tls:
    existingSecret: secret-tls
